# permissions for end users to view policyengineendpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: policyengineendpoint-viewer-role
rules:
- apiGroups:
  - anti.no.anti.no
  resources:
  - policyengineendpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - anti.no.anti.no
  resources:
  - policyengineendpoints/status
  verbs:
  - get
